export type HuntingSpotData = {
  id: string;
  name: string;
  levelRange: [number, number];
  location: string;
  expRaw: number;
  expBonus: number;
  profit: number;
  supplyCost: number;
  set: string;
  imbuements: string[];
  notes: string;
};

export type HuntingSpotsByVocation = Record<string, HuntingSpotData[]>;

export function formatRate(n: number): string {
  if (n >= 1_000_000) {
    const val = n / 1_000_000;
    return `${val % 1 === 0 ? val.toFixed(0) : val.toFixed(1)}kk/h`;
  }
  return `${(n / 1_000).toFixed(0)}k/h`;
}

export function formatProfit(n: number): string {
  const prefix = n < 0 ? '-' : '';
  const abs = Math.abs(n);
  if (abs >= 1_000_000) {
    return `${prefix}${(abs / 1_000_000).toFixed(1)}kk/h`;
  }
  return `${prefix}${(abs / 1_000).toFixed(0)}k/h`;
}

export function calculateHoursToLevel(
  currentLevel: number,
  currentPercent: number,
  targetLevel: number,
  expPerHour: number,
): number | null {
  if (currentLevel < 1 || targetLevel <= currentLevel || expPerHour <= 0) return null;

  const cumulativeXp = (lvl: number) =>
    Math.floor((50 / 3) * lvl * lvl * lvl - 100 * lvl * lvl + (850 / 3) * lvl - 200);

  const currentXp = cumulativeXp(currentLevel);
  const currentXpIntoNext = (currentPercent / 100) * (cumulativeXp(currentLevel + 1) - currentXp);
  const totalXpNow = currentXp + currentXpIntoNext;
  const totalXpTarget = cumulativeXp(targetLevel);

  const xpNeeded = totalXpTarget - totalXpNow;
  if (xpNeeded <= 0) return 0;

  return xpNeeded / expPerHour;
}

export function calculateHoursToNextLevel(
  currentLevel: number,
  currentPercent: number,
  expPerHour: number,
): number | null {
  return calculateHoursToLevel(currentLevel, currentPercent, currentLevel + 1, expPerHour);
}

export function formatHours(hours: number): string {
  if (hours < 1) return `${Math.round(hours * 60)} min`;
  const h = Math.floor(hours);
  const m = Math.round((hours - h) * 60);
  if (m === 0) return `${h}h`;
  return `${h}h ${m}m`;
}

export const huntingSpotsByVocation: HuntingSpotsByVocation = {
  knight: [
    {
      id: 'knight-carlin-cults',
      name: 'Carlin Cults',
      levelRange: [50, 120],
      location: 'Carlin',
      expRaw: 400_000,
      expBonus: 600_000,
      profit: 100_000,
      supplyCost: 30_000,
      set: 'Zaoan set, Garlic Necklace, Stone Skin Amulet',
      imbuements: ['Critical', 'Void', 'Vampirism'],
      notes: 'Good for early EK. Bring fire bombs for safety.',
    },
    {
      id: 'knight-edron-vampires',
      name: 'Edron Vampires',
      levelRange: [80, 150],
      location: 'Edron',
      expRaw: 600_000,
      expBonus: 900_000,
      profit: 150_000,
      supplyCost: 40_000,
      set: 'Dwarven set, Garlic Necklace, Werewolf Amulet',
      imbuements: ['Critical', 'Void', 'Vampirism'],
      notes: 'Silence of the Lost Palace. Bring garlic necklaces.',
    },
    {
      id: 'knight-seacrest-serpents',
      name: 'Seacrest Serpents',
      levelRange: [100, 200],
      location: 'Seacrest Grounds',
      expRaw: 900_000,
      expBonus: 1_300_000,
      profit: 200_000,
      supplyCost: 50_000,
      set: 'Ornate set, Terra Helmet',
      imbuements: ['Critical', 'Void', 'Vampirism', 'Terra'],
      notes: 'Watch for quara scouts. Use energy/terra protection.',
    },
    {
      id: 'knight-krailos-nightmares',
      name: 'Krailos Nightmares',
      levelRange: [150, 300],
      location: 'Krailos',
      expRaw: 1_500_000,
      expBonus: 2_200_000,
      profit: 250_000,
      supplyCost: 60_000,
      set: 'Ornate set, Depth Calcei, Falcon Greaves',
      imbuements: ['Critical', 'Void', 'Vampirism', 'Death'],
      notes: 'Nightmares are weak to death. Bring death protection.',
    },
    {
      id: 'knight-banuta',
      name: 'Banuta',
      levelRange: [130, 250],
      location: 'Banuta',
      expRaw: 1_200_000,
      expBonus: 1_800_000,
      profit: 300_000,
      supplyCost: 50_000,
      set: 'Ornate set, Terra Helmet, Depth Calcei',
      imbuements: ['Critical', 'Void', 'Vampirism', 'Fire'],
      notes: 'Serpent spawns. Use fire protection. Be careful of pulls.',
    },
    {
      id: 'knight-draken-walls',
      name: 'Draken Walls',
      levelRange: [180, 350],
      location: 'Zao',
      expRaw: 2_000_000,
      expBonus: 3_000_000,
      profit: 350_000,
      supplyCost: 70_000,
      set: 'Soul set, Falcon Escutcheon, Falcon Greaves',
      imbuements: ['Critical', 'Void', 'Vampirism', 'Death'],
      notes: 'Need access. Bring death protection and walls.',
    },
    {
      id: 'knight-lower-roshamuul',
      name: 'Lower Roshamuul',
      levelRange: [200, 400],
      location: 'Roshamuul',
      expRaw: 2_500_000,
      expBonus: 3_500_000,
      profit: 400_000,
      supplyCost: 80_000,
      set: 'Soul set, Falcon Escutcheon',
      imbuements: ['Critical', 'Void', 'Vampirism', 'Death'],
      notes: 'Need access to Roshamuul. Bring death protection.',
    },
    {
      id: 'knight-buried-cathedral',
      name: 'Buried Cathedral',
      levelRange: [250, 500],
      location: 'Darashia',
      expRaw: 3_000_000,
      expBonus: 4_500_000,
      profit: 500_000,
      supplyCost: 100_000,
      set: 'Soul set, Lion Shield, Falcon Greaves',
      imbuements: ['Critical', 'Void', 'Vampirism', 'Holy'],
      notes: 'Soulfire is dangerous. Bring holy protection and might rings.',
    },
    {
      id: 'knight-issavi-sphinx',
      name: 'Issavi Sphinx / Lamassu',
      levelRange: [300, 600],
      location: 'Issavi',
      expRaw: 3_500_000,
      expBonus: 5_000_000,
      profit: 600_000,
      supplyCost: 120_000,
      set: 'Soul set, Lion Shield, Falcon Greaves',
      imbuements: ['Critical', 'Void', 'Vampirism', 'Holy'],
      notes: 'Excellent exp. Bring might rings and holy protection.',
    },
    {
      id: 'knight-ferumbras-ascendant',
      name: 'Ferumbras Ascendant',
      levelRange: [400, 800],
      location: 'Ferumbras Citadel',
      expRaw: 4_500_000,
      expBonus: 6_500_000,
      profit: 700_000,
      supplyCost: 150_000,
      set: 'Soul set, Lion Shield, Eldritch Greaves',
      imbuements: ['Critical', 'Void', 'Vampirism', 'Death'],
      notes: 'Endgame spawn. Need full BiS. Bring death/holy protection.',
    },
  ],

  paladin: [
    {
      id: 'paladin-lb-cults',
      name: 'Liberty Bay Cults',
      levelRange: [50, 100],
      location: 'Liberty Bay',
      expRaw: 350_000,
      expBonus: 500_000,
      profit: 80_000,
      supplyCost: 25_000,
      set: 'Paladin armor, Zaoan Helmet, Composite Hornbow',
      imbuements: ['Critical', 'Void'],
      notes: 'Yalahar quest access helps. Use fire walls.',
    },
    {
      id: 'paladin-oro-cult',
      name: 'Oramond Cult Minos',
      levelRange: [80, 150],
      location: 'Oramond',
      expRaw: 600_000,
      expBonus: 900_000,
      profit: 150_000,
      supplyCost: 35_000,
      set: 'Elite Draken set, Warsinger Bow',
      imbuements: ['Critical', 'Void'],
      notes: 'Use energy walls and fire walls.',
    },
    {
      id: 'paladin-deeplings',
      name: 'Deeplings',
      levelRange: [130, 250],
      location: 'Liberty Bay',
      expRaw: 1_200_000,
      expBonus: 1_800_000,
      profit: 300_000,
      supplyCost: 50_000,
      set: 'Elite Draken set, Bow of Destruction, Living Bow',
      imbuements: ['Critical', 'Void', 'Parry'],
      notes: 'Use energy walls. Bring e-ring for emergency.',
    },
    {
      id: 'paladin-gnomprona-surface',
      name: 'Gnomprona Surface',
      levelRange: [100, 200],
      location: 'Gnomprona',
      expRaw: 900_000,
      expBonus: 1_400_000,
      profit: 200_000,
      supplyCost: 40_000,
      set: 'Elite Draken set, Bow of Destruction',
      imbuements: ['Critical', 'Void', 'Parry'],
      notes: 'Glooth and gnome spawn. Bring physical protection.',
    },
    {
      id: 'paladin-werehyaenas',
      name: 'Werehyaenas',
      levelRange: [150, 300],
      location: 'Tiquanda',
      expRaw: 1_800_000,
      expBonus: 2_700_000,
      profit: 350_000,
      supplyCost: 60_000,
      set: 'Gnome set, Bow of Destruction, Soulshredder',
      imbuements: ['Critical', 'Void', 'Parry', 'Holy'],
      notes: 'Great exp for RP. Bring holy protection and walls.',
    },
    {
      id: 'paladin-draken-walls',
      name: 'Draken Walls',
      levelRange: [180, 350],
      location: 'Zao',
      expRaw: 2_200_000,
      expBonus: 3_300_000,
      profit: 400_000,
      supplyCost: 70_000,
      set: 'Gnome set, Bow of Destruction, Soulshredder',
      imbuements: ['Critical', 'Void', 'Parry', 'Death'],
      notes: 'Bring death protection. Diamond arrows recommended.',
    },
    {
      id: 'paladin-roshamuul',
      name: 'Roshamuul',
      levelRange: [200, 400],
      location: 'Roshamuul',
      expRaw: 2_500_000,
      expBonus: 3_500_000,
      profit: 500_000,
      supplyCost: 80_000,
      set: 'Gnome set, Bow of Destruction, Soulshredder',
      imbuements: ['Critical', 'Void', 'Parry'],
      notes: 'Need access quest. Use death protection.',
    },
    {
      id: 'paladin-buried-cathedral',
      name: 'Buried Cathedral',
      levelRange: [250, 500],
      location: 'Darashia',
      expRaw: 3_200_000,
      expBonus: 4_800_000,
      profit: 550_000,
      supplyCost: 100_000,
      set: 'Falcon set, Soulshredder, Eldritch Bow',
      imbuements: ['Critical', 'Void', 'Parry', 'Holy'],
      notes: 'Soulfire and spectres. Diamond arrows + holy.',
    },
    {
      id: 'paladin-nightmare',
      name: 'Nightmare Isles',
      levelRange: [250, 500],
      location: 'Nightmare Island',
      expRaw: 3_000_000,
      expBonus: 4_500_000,
      profit: 600_000,
      supplyCost: 100_000,
      set: 'Falcon set, Soulshredder, Eldritch Bow',
      imbuements: ['Critical', 'Void', 'Parry', 'Holy'],
      notes: 'Need access. Bring holy protection.',
    },
    {
      id: 'paladin-ferumbras-ascendant',
      name: 'Ferumbras Ascendant',
      levelRange: [400, 800],
      location: 'Ferumbras Citadel',
      expRaw: 4_000_000,
      expBonus: 6_000_000,
      profit: 750_000,
      supplyCost: 150_000,
      set: 'Falcon set, Eldritch Bow, Soulshredder',
      imbuements: ['Critical', 'Void', 'Parry', 'Death'],
      notes: 'Endgame RP spawn. Use diamond arrows + death protection.',
    },
  ],

  sorcerer: [
    {
      id: 'sorcerer-dragons',
      name: 'Dragons / Dragon Lords',
      levelRange: [40, 100],
      location: 'Darashia / Venore',
      expRaw: 300_000,
      expBonus: 450_000,
      profit: 100_000,
      supplyCost: 40_000,
      set: 'Blue Set, Spellbook',
      imbuements: ['Critical', 'Void', 'Parry'],
      notes: 'Classic SD route. Bring fire protection.',
    },
    {
      id: 'sorcerer-oramond-minos',
      name: 'Oramond Minos',
      levelRange: [60, 130],
      location: 'Oramond',
      expRaw: 500_000,
      expBonus: 750_000,
      profit: 120_000,
      supplyCost: 40_000,
      set: 'Yalahari set, Wand of Destruction',
      imbuements: ['Critical', 'Void'],
      notes: 'SD + waves. Use terra set.',
    },
    {
      id: 'sorcerer-lava-lurkers',
      name: 'Lava Lurkers',
      levelRange: [80, 200],
      location: 'Krailos',
      expRaw: 900_000,
      expBonus: 1_400_000,
      profit: 50_000,
      supplyCost: 30_000,
      set: 'Yalahari set, Wand of Destruction',
      imbuements: ['Critical', 'Void'],
      notes: 'Low loot but best exp for MS. Use energy ring.',
    },
    {
      id: 'sorcerer-oramond-gladiators',
      name: 'Oramond Gladiators',
      levelRange: [100, 200],
      location: 'Oramond',
      expRaw: 1_000_000,
      expBonus: 1_500_000,
      profit: 150_000,
      supplyCost: 45_000,
      set: 'Gnome set, Wand of Destruction',
      imbuements: ['Critical', 'Void', 'Parry'],
      notes: 'Good for MS. Use energy walls.',
    },
    {
      id: 'sorcerer-carnivors',
      name: 'Carnivors',
      levelRange: [120, 220],
      location: 'Darashia',
      expRaw: 1_200_000,
      expBonus: 1_800_000,
      profit: 200_000,
      supplyCost: 50_000,
      set: 'Gnome set, Wand of Destruction, Falcon Wand',
      imbuements: ['Critical', 'Void', 'Parry'],
      notes: 'Use fire and energy walls.',
    },
    {
      id: 'sorcerer-werehyaenas',
      name: 'Werehyaenas',
      levelRange: [150, 300],
      location: 'Tiquanda',
      expRaw: 2_000_000,
      expBonus: 3_000_000,
      profit: 300_000,
      supplyCost: 60_000,
      set: 'Falcon set, Wand of Destruction, Falcon Wand',
      imbuements: ['Critical', 'Void', 'Parry', 'Holy'],
      notes: 'Great exp for MS. Bring holy protection.',
    },
    {
      id: 'sorcerer-winter-elf',
      name: 'Winter Elves',
      levelRange: [200, 400],
      location: 'Gnomprona',
      expRaw: 2_800_000,
      expBonus: 4_000_000,
      profit: 400_000,
      supplyCost: 80_000,
      set: 'Falcon set, Wand of Destruction, Soultaint',
      imbuements: ['Critical', 'Void', 'Parry', 'Death'],
      notes: 'Need access. Bring death and ice protection.',
    },
    {
      id: 'sorcerer-gazer-spectre',
      name: 'Gazer / Spectre',
      levelRange: [200, 400],
      location: 'Alchemist Quarter',
      expRaw: 2_500_000,
      expBonus: 3_800_000,
      profit: 350_000,
      supplyCost: 75_000,
      set: 'Falcon set, Soultaint, Eldritch Wand',
      imbuements: ['Critical', 'Void', 'Parry', 'Death'],
      notes: 'Bring death protection. Beware of gazer one-shots.',
    },
    {
      id: 'sorcerer-buried-cathedral',
      name: 'Buried Cathedral',
      levelRange: [250, 500],
      location: 'Darashia',
      expRaw: 3_500_000,
      expBonus: 5_200_000,
      profit: 500_000,
      supplyCost: 100_000,
      set: 'Falcon set, Soultaint, Eldritch Wand',
      imbuements: ['Critical', 'Void', 'Parry', 'Holy'],
      notes: 'Top MS spawn. Use UE on cooldown.',
    },
    {
      id: 'sorcerer-ferumbras-ascendant',
      name: 'Ferumbras Ascendant',
      levelRange: [400, 800],
      location: 'Ferumbras Citadel',
      expRaw: 5_000_000,
      expBonus: 7_500_000,
      profit: 600_000,
      supplyCost: 150_000,
      set: 'Falcon set, Eldritch Wand, Soultaint',
      imbuements: ['Critical', 'Void', 'Parry', 'Death'],
      notes: 'Endgame MS. Use full BiS and death protection.',
    },
  ],

  druid: [
    {
      id: 'druid-ancient-scarabs',
      name: 'Ancient Scarabs',
      levelRange: [30, 80],
      location: 'Ankrahmun',
      expRaw: 250_000,
      expBonus: 400_000,
      profit: 80_000,
      supplyCost: 25_000,
      set: 'Blue Set, Spellbook',
      imbuements: ['Critical', 'Void', 'Parry'],
      notes: 'Classic low-mid level spot. Bring terra protection.',
    },
    {
      id: 'druid-oramond-gladiators',
      name: 'Oramond Gladiators',
      levelRange: [100, 200],
      location: 'Oramond',
      expRaw: 1_000_000,
      expBonus: 1_500_000,
      profit: 150_000,
      supplyCost: 45_000,
      set: 'Gnome set, Wand of Destruction',
      imbuements: ['Critical', 'Void', 'Parry'],
      notes: 'Good for ED. Use ice waves + energy walls.',
    },
    {
      id: 'druid-asuras',
      name: 'Asura Palace',
      levelRange: [120, 250],
      location: 'Darashia',
      expRaw: 1_500_000,
      expBonus: 2_200_000,
      profit: 250_000,
      supplyCost: 55_000,
      set: 'Gnome set, Falcon Wand, Wand of Destruction',
      imbuements: ['Critical', 'Void', 'Parry', 'Fire'],
      notes: 'High risk high reward. Use fire protection.',
    },
    {
      id: 'druid-issavi-sphinx',
      name: 'Issavi Sphinx / Lamassu',
      levelRange: [150, 350],
      location: 'Issavi',
      expRaw: 2_000_000,
      expBonus: 3_000_000,
      profit: 350_000,
      supplyCost: 65_000,
      set: 'Falcon set, Wand of Destruction, Soultaint',
      imbuements: ['Critical', 'Void', 'Parry', 'Holy'],
      notes: 'Best spawn for ED. Use holy protection.',
    },
    {
      id: 'druid-werehyaenas',
      name: 'Werehyaenas',
      levelRange: [150, 300],
      location: 'Tiquanda',
      expRaw: 1_800_000,
      expBonus: 2_700_000,
      profit: 300_000,
      supplyCost: 60_000,
      set: 'Falcon set, Soultaint, Falcon Wand',
      imbuements: ['Critical', 'Void', 'Parry', 'Holy'],
      notes: 'Bring holy protection. Strong for ED.',
    },
    {
      id: 'druid-cobra',
      name: 'Cobra Bastion',
      levelRange: [200, 400],
      location: 'Bastia',
      expRaw: 2_500_000,
      expBonus: 3_800_000,
      profit: 500_000,
      supplyCost: 90_000,
      set: 'Falcon set, Soultaint, Eldritch Wand',
      imbuements: ['Critical', 'Void', 'Parry', 'Earth'],
      notes: 'Need access. Bring physical/earth protection.',
    },
    {
      id: 'druid-gazer-spectre',
      name: 'Gazer / Spectre',
      levelRange: [200, 400],
      location: 'Alchemist Quarter',
      expRaw: 2_500_000,
      expBonus: 3_800_000,
      profit: 350_000,
      supplyCost: 75_000,
      set: 'Falcon set, Soultaint, Eldritch Wand',
      imbuements: ['Critical', 'Void', 'Parry', 'Death'],
      notes: 'Bring death protection. Strong ice waves.',
    },
    {
      id: 'druid-roshe',
      name: 'Roshamuul Prison',
      levelRange: [250, 500],
      location: 'Roshamuul',
      expRaw: 3_000_000,
      expBonus: 4_500_000,
      profit: 600_000,
      supplyCost: 100_000,
      set: 'Falcon set, Soultaint, Eldritch Wand',
      imbuements: ['Critical', 'Void', 'Parry', 'Death'],
      notes: 'Need access. Bring death protection and poison bombs.',
    },
    {
      id: 'druid-buried-cathedral',
      name: 'Buried Cathedral',
      levelRange: [250, 500],
      location: 'Darashia',
      expRaw: 3_200_000,
      expBonus: 4_800_000,
      profit: 500_000,
      supplyCost: 100_000,
      set: 'Falcon set, Soultaint, Eldritch Wand',
      imbuements: ['Critical', 'Void', 'Parry', 'Holy'],
      notes: 'Top ED spawn. Ice UE on cooldown.',
    },
    {
      id: 'druid-ferumbras-ascendant',
      name: 'Ferumbras Ascendant',
      levelRange: [400, 800],
      location: 'Ferumbras Citadel',
      expRaw: 4_500_000,
      expBonus: 6_500_000,
      profit: 600_000,
      supplyCost: 150_000,
      set: 'Falcon set, Eldritch Wand, Soultaint',
      imbuements: ['Critical', 'Void', 'Parry', 'Death'],
      notes: 'Endgame ED. Full BiS, death protection, ice UE.',
    },
  ],

  monk: [
    {
      id: 'monk-stonerefiners',
      name: 'Stonerefiners',
      levelRange: [30, 80],
      location: 'Krailos',
      expRaw: 250_000,
      expBonus: 400_000,
      profit: 60_000,
      supplyCost: 15_000,
      set: 'Basic physical set, Werewolf Amulet',
      imbuements: ['Critical', 'Vampirism'],
      notes: 'Good early spot for testing Monk abilities.',
    },
    {
      id: 'monk-goroma-mad-sheep',
      name: 'Goroma Mad Sheep / Tortoises',
      levelRange: [40, 100],
      location: 'Goroma',
      expRaw: 350_000,
      expBonus: 500_000,
      profit: 80_000,
      supplyCost: 20_000,
      set: 'Blue set, Terra Amulet',
      imbuements: ['Critical', 'Vampirism'],
      notes: 'Good for testing Monk burst damage.',
    },
    {
      id: 'monk-yalahar-bog',
      name: 'Yalahar Bog Raiders',
      levelRange: [50, 120],
      location: 'Yalahar',
      expRaw: 400_000,
      expBonus: 600_000,
      profit: 100_000,
      supplyCost: 25_000,
      set: 'Zaoan set, Koshei\'s Amulet',
      imbuements: ['Critical', 'Void', 'Vampirism'],
      notes: 'Bog Raiders are weak to physical.',
    },
    {
      id: 'monk-banuta',
      name: 'Banuta',
      levelRange: [130, 250],
      location: 'Banuta',
      expRaw: 1_200_000,
      expBonus: 1_800_000,
      profit: 300_000,
      supplyCost: 50_000,
      set: 'Ornate set, Gnome Armor, Falcon Greaves',
      imbuements: ['Critical', 'Void', 'Vampirism'],
      notes: 'Monk physical resistance helps. Use fire protection.',
    },
    {
      id: 'monk-deeplings',
      name: 'Deeplings',
      levelRange: [130, 250],
      location: 'Liberty Bay',
      expRaw: 1_000_000,
      expBonus: 1_500_000,
      profit: 300_000,
      supplyCost: 50_000,
      set: 'Ornate set, Gnome Armor, Falcon Greaves',
      imbuements: ['Critical', 'Void', 'Vampirism'],
      notes: 'Use energy walls. Monk physical resistance helps.',
    },
    {
      id: 'monk-krailos-nightmares',
      name: 'Krailos Nightmares',
      levelRange: [150, 300],
      location: 'Krailos',
      expRaw: 1_500_000,
      expBonus: 2_200_000,
      profit: 250_000,
      supplyCost: 60_000,
      set: 'Ornate set, Soul Mantle, Falcon Greaves',
      imbuements: ['Critical', 'Void', 'Vampirism', 'Death'],
      notes: 'Monk anti-knockback is strong here.',
    },
    {
      id: 'monk-draken-walls',
      name: 'Draken Walls',
      levelRange: [180, 350],
      location: 'Zao',
      expRaw: 2_000_000,
      expBonus: 3_000_000,
      profit: 400_000,
      supplyCost: 70_000,
      set: 'Soul set, Lion Plate, Falcon Greaves',
      imbuements: ['Critical', 'Void', 'Vampirism', 'Death'],
      notes: 'Monk excels in tight spaces. Good for AoE farming.',
    },
    {
      id: 'monk-oramond-catacombs',
      name: 'Oramond Catacombs',
      levelRange: [200, 400],
      location: 'Oramond',
      expRaw: 2_200_000,
      expBonus: 3_300_000,
      profit: 450_000,
      supplyCost: 80_000,
      set: 'Soul set, Lion Plate, Falcon Greaves',
      imbuements: ['Critical', 'Void', 'Vampirism', 'Parry'],
      notes: 'Dense spawns. Monk AoE shines here.',
    },
    {
      id: 'monk-pirats',
      name: 'Pirats',
      levelRange: [200, 400],
      location: 'Pirat Bay',
      expRaw: 2_000_000,
      expBonus: 3_000_000,
      profit: 500_000,
      supplyCost: 80_000,
      set: 'Soul set, Lion Plate, Falcon Greaves',
      imbuements: ['Critical', 'Void', 'Vampirism', 'Parry'],
      notes: 'Great loot. Monk anti-knockback passive is useful here.',
    },
    {
      id: 'monk-ferumbras-ascendant',
      name: 'Ferumbras Ascendant',
      levelRange: [400, 800],
      location: 'Ferumbras Citadel',
      expRaw: 4_000_000,
      expBonus: 6_000_000,
      profit: 700_000,
      supplyCost: 150_000,
      set: 'Soul set, Lion Plate, Eldritch Greaves',
      imbuements: ['Critical', 'Void', 'Vampirism', 'Death'],
      notes: 'Endgame Monk. Monk passives provide survivability.',
    },
  ],
};
