export type HuntingSpotData = {
  id: string;
  name: string;
  levelRange: [number, number];
  location: string;
  expRaw: string;
  expBonus: string;
  loot: string;
  set: string;
  imbuements: string[];
  notes: string;
};

export type HuntingSpotsByVocation = Record<string, HuntingSpotData[]>;

export const huntingSpotsByVocation: HuntingSpotsByVocation = {
  knight: [
    {
      id: 'knight-carlin-cults',
      name: 'Carlin Cults',
      levelRange: [50, 120],
      location: 'Carlin',
      expRaw: '400k/h',
      expBonus: '600k/h',
      loot: '100k/h',
      set: 'Zaoan set, Garlic Necklace, Stone Skin Amulet',
      imbuements: ['Critical', 'Void', 'Vampirism'],
      notes: 'Good for early EK. Bring fire bombs for safety.',
    },
    {
      id: 'knight-edron-vampires',
      name: 'Edron Vampires',
      levelRange: [80, 150],
      location: 'Edron',
      expRaw: '600k/h',
      expBonus: '900k/h',
      loot: '150k/h',
      set: 'Dwarven set, Garlic Necklace, Werewolf Amulet',
      imbuements: ['Critical', 'Void', 'Vampirism'],
      notes: 'Silence of the Lost Palace. Bring garlic necklaces.',
    },
    {
      id: 'knight-seacrest-serpents',
      name: 'Seacrest Serpents',
      levelRange: [100, 200],
      location: 'Seacrest Grounds',
      expRaw: '900k/h',
      expBonus: '1.3kk/h',
      loot: '200k/h',
      set: 'Ornate set, Terra Helmet',
      imbuements: ['Critical', 'Void', 'Vampirism', 'Terra'],
      notes: 'Watch for quara scouts. Use energy/terra protection.',
    },
    {
      id: 'knight-lower-roshamuul',
      name: 'Lower Roshamuul',
      levelRange: [200, 400],
      location: 'Roshamuul',
      expRaw: '2.5kk/h',
      expBonus: '3.5kk/h',
      loot: '400k/h',
      set: 'Soul set, Falcon Escutcheon',
      imbuements: ['Critical', 'Void', 'Vampirism', 'Death'],
      notes: 'Need access to Roshamuul. Bring death protection.',
    },
    {
      id: 'knight-issavi-sphinx',
      name: 'Issavi Sphinx / Lamassu',
      levelRange: [300, 600],
      location: 'Issavi',
      expRaw: '3.5kk/h',
      expBonus: '5kk/h',
      loot: '600k/h',
      set: 'Soul set, Lion Shield, Falcon Greaves',
      imbuements: ['Critical', 'Void', 'Vampirism', 'Holy'],
      notes: 'Excellent exp. Bring might rings and holy protection.',
    },
  ],

  paladin: [
    {
      id: 'paladin-lb-cults',
      name: 'Liberty Bay Cults',
      levelRange: [50, 100],
      location: 'Liberty Bay',
      expRaw: '350k/h',
      expBonus: '500k/h',
      loot: '80k/h',
      set: 'Paladin armor, Zaoan Helmet, Composite Hornbow',
      imbuements: ['Critical', 'Void'],
      notes: 'Yalahar quest access helps. Use fire walls.',
    },
    {
      id: 'paladin-oro-cult',
      name: 'Oramond Cult Minos',
      levelRange: [80, 150],
      location: 'Oramond',
      expRaw: '600k/h',
      expBonus: '900k/h',
      loot: '150k/h',
      set: 'Elite Draken set, Warsinger Bow',
      imbuements: ['Critical', 'Void'],
      notes: 'Use energy walls and fire walls.',
    },
    {
      id: 'paladin-deeplings',
      name: 'Deeplings',
      levelRange: [130, 250],
      location: 'Liberty Bay',
      expRaw: '1.2kk/h',
      expBonus: '1.8kk/h',
      loot: '300k/h',
      set: 'Elite Draken set, Bow of Destruction, Living Bow',
      imbuements: ['Critical', 'Void', 'Parry'],
      notes: 'Use energy walls. Bring e-ring for emergency.',
    },
    {
      id: 'paladin-roshamuul',
      name: 'Roshamuul',
      levelRange: [200, 400],
      location: 'Roshamuul',
      expRaw: '2.5kk/h',
      expBonus: '3.5kk/h',
      loot: '500k/h',
      set: 'Gnome set, Bow of Destruction, Soulshredder',
      imbuements: ['Critical', 'Void', 'Parry'],
      notes: 'Need access quest. Use death protection.',
    },
    {
      id: 'paladin-nightmare',
      name: 'Nightmare Isles',
      levelRange: [250, 500],
      location: 'Nightmare Island',
      expRaw: '3kk/h',
      expBonus: '4.5kk/h',
      loot: '600k/h',
      set: 'Falcon set, Soulshredder, Eldritch Bow',
      imbuements: ['Critical', 'Void', 'Parry', 'Holy'],
      notes: 'Need access. Bring holy protection.',
    },
  ],

  sorcerer: [
    {
      id: 'sorcerer-dragons',
      name: 'Dragons / Dragon Lords',
      levelRange: [40, 100],
      location: 'Darashia / Venore',
      expRaw: '300k/h',
      expBonus: '450k/h',
      loot: '100k/h',
      set: 'Blue Set, Spellbook',
      imbuements: ['Critical', 'Void', 'Parry'],
      notes: 'Classic SD route. Bring fire protection.',
    },
    {
      id: 'sorcerer-oramond-minos',
      name: 'Oramond Minos',
      levelRange: [60, 130],
      location: 'Oramond',
      expRaw: '500k/h',
      expBonus: '750k/h',
      loot: '120k/h',
      set: 'Yalahari set, Wand of Destruction',
      imbuements: ['Critical', 'Void'],
      notes: 'SD + waves. Use terra set.',
    },
    {
      id: 'sorcerer-lava-lurkers',
      name: 'Lava Lurkers',
      levelRange: [80, 200],
      location: 'Krailos',
      expRaw: '900k/h',
      expBonus: '1.4kk/h',
      loot: '50k/h',
      set: 'Yalahari set, Wand of Destruction',
      imbuements: ['Critical', 'Void'],
      notes: 'Low loot but best exp for MS. Use energy ring.',
    },
    {
      id: 'sorcerer-carnivors',
      name: 'Carnivors',
      levelRange: [120, 220],
      location: 'Darashia',
      expRaw: '1.2kk/h',
      expBonus: '1.8kk/h',
      loot: '200k/h',
      set: 'Gnome set, Wand of Destruction, Falcon Wand',
      imbuements: ['Critical', 'Void', 'Parry'],
      notes: 'Use fire and energy walls.',
    },
    {
      id: 'sorcerer-winter-elf',
      name: 'Winter Elves',
      levelRange: [200, 400],
      location: 'Gnomprona',
      expRaw: '2.8kk/h',
      expBonus: '4kk/h',
      loot: '400k/h',
      set: 'Falcon set, Wand of Destruction, Soultaint',
      imbuements: ['Critical', 'Void', 'Parry', 'Death'],
      notes: 'Need access. Bring death and ice protection.',
    },
  ],

  druid: [
    {
      id: 'druid-ancient-scarabs',
      name: 'Ancient Scarabs',
      levelRange: [30, 80],
      location: 'Ankrahmun',
      expRaw: '250k/h',
      expBonus: '400k/h',
      loot: '80k/h',
      set: 'Blue Set, Spellbook',
      imbuements: ['Critical', 'Void', 'Parry'],
      notes: 'Classic low-mid level spot. Bring terra protection.',
    },
    {
      id: 'druid-issavi-sphinx',
      name: 'Issavi Sphinx / Lamassu',
      levelRange: [150, 350],
      location: 'Issavi',
      expRaw: '2kk/h',
      expBonus: '3kk/h',
      loot: '350k/h',
      set: 'Falcon set, Wand of Destruction, Soultaint',
      imbuements: ['Critical', 'Void', 'Parry', 'Holy'],
      notes: 'Best spawn for ED. Use holy protection.',
    },
    {
      id: 'druid-asuras',
      name: 'Asura Palace',
      levelRange: [120, 250],
      location: 'Darashia',
      expRaw: '1.5kk/h',
      expBonus: '2.2kk/h',
      loot: '250k/h',
      set: 'Gnome set, Falcon Wand, Wand of Destruction',
      imbuements: ['Critical', 'Void', 'Parry', 'Fire'],
      notes: 'High risk high reward. Use fire protection.',
    },
    {
      id: 'druid-cobra',
      name: 'Cobra Bastion',
      levelRange: [200, 400],
      location: 'Bastia',
      expRaw: '2.5kk/h',
      expBonus: '3.8kk/h',
      loot: '500k/h',
      set: 'Falcon set, Soultaint, Eldritch Wand',
      imbuements: ['Critical', 'Void', 'Parry', 'Earth'],
      notes: 'Need access. Bring physical/earth protection.',
    },
    {
      id: 'druid-roshe',
      name: 'Roshamuul Prison',
      levelRange: [250, 500],
      location: 'Roshamuul',
      expRaw: '3kk/h',
      expBonus: '4.5kk/h',
      loot: '600k/h',
      set: 'Falcon set, Soultaint, Eldritch Wand',
      imbuements: ['Critical', 'Void', 'Parry', 'Death'],
      notes: 'Need access. Bring death protection and poison bombs.',
    },
  ],

  monk: [
    {
      id: 'monk-stonerefiners',
      name: 'Stonerefiners',
      levelRange: [30, 80],
      location: 'Krailos',
      expRaw: '250k/h',
      expBonus: '400k/h',
      loot: '60k/h',
      set: 'Basic physical set, Werewolf Amulet',
      imbuements: ['Critical', 'Vampirism'],
      notes: 'Good early spot for testing Monk abilities.',
    },
    {
      id: 'monk-yalahar-bog',
      name: 'Yalahar Bog Raiders',
      levelRange: [50, 120],
      location: 'Yalahar',
      expRaw: '400k/h',
      expBonus: '600k/h',
      loot: '100k/h',
      set: 'Zaoan set, Koshei\'s Amulet',
      imbuements: ['Critical', 'Void', 'Vampirism'],
      notes: 'Bog Raiders are weak to physical.',
    },
    {
      id: 'monk-goroma-mad-sheep',
      name: 'Goroma Mad Sheep / Tortoises',
      levelRange: [40, 100],
      location: 'Goroma',
      expRaw: '350k/h',
      expBonus: '500k/h',
      loot: '80k/h',
      set: 'Blue set, Terra Amulet',
      imbuements: ['Critical', 'Vampirism'],
      notes: 'Good for testing Monk burst damage.',
    },
    {
      id: 'monk-deeplings',
      name: 'Deeplings',
      levelRange: [130, 250],
      location: 'Liberty Bay',
      expRaw: '1kk/h',
      expBonus: '1.5kk/h',
      loot: '300k/h',
      set: 'Ornate set, Gnome Armor, Falcon Greaves',
      imbuements: ['Critical', 'Void', 'Vampirism'],
      notes: 'Use energy walls. Monk physical resistance helps.',
    },
    {
      id: 'monk-pirats',
      name: 'Pirats',
      levelRange: [200, 400],
      location: 'Pirat Bay',
      expRaw: '2kk/h',
      expBonus: '3kk/h',
      loot: '500k/h',
      set: 'Soul set, Lion Plate, Falcon Greaves',
      imbuements: ['Critical', 'Void', 'Vampirism', 'Parry'],
      notes: 'Great loot. Monk anti-knockback passive is useful here.',
    },
  ],
};
