import { ImbuableItem } from "./imbuableItems";

export const armors: ImbuableItem[] = [
  { name: "Albino Plate", icon: "", imbuingSlots: 2 },
  { name: "Amazon Armor", icon: "", imbuingSlots: 2 },
  { name: "Arcane Dragon Robe", icon: "", imbuingSlots: 1, elements: ["ice"] },
  { name: "Bear Skin", icon: "", imbuingSlots: 1, elements: ["earth"] },
  { name: "Blue Robe", icon: "", imbuingSlots: 2 },
  { name: "Chain Armor", icon: "", imbuingSlots: 2 },
  { name: "Crown Armor", icon: "", imbuingSlots: 1 },
  {
    name: "Dauntless Dragon Scale Armor",
    icon: "",
    imbuingSlots: 2,
  },
  { name: "Dawnfire Sherwani", icon: "", imbuingSlots: 1, elements: ["fire"] },
  { name: "Death Oyoroi", icon: "", imbuingSlots: 1, elements: ["death"] },
  { name: "Demon Armor", icon: "", imbuingSlots: 2 },
  { name: "Depth Lorica", icon: "", imbuingSlots: 2, elements: ["death"] },
  { name: "Dragon Scale Mail", icon: "", imbuingSlots: 1 },
  { name: "Dream Shroud", icon: "", imbuingSlots: 1, elements: ["energy"] },
  { name: "Dwarven Armor", icon: "", imbuingSlots: 2 },
  { name: "Eldritch Cuirass", icon: "", imbuingSlots: 2 },
  { name: "Elite Draken Mail", icon: "", imbuingSlots: 2 },
  { name: "Elven Mail", icon: "", imbuingSlots: 3 },
  { name: "Embrace of Nature", icon: "", imbuingSlots: 1, elements: ["ice"] },
  { name: "Falcon Plate", icon: "", imbuingSlots: 2 },
  { name: "Ghost Chestplate", icon: "", imbuingSlots: 2 },
  { name: "Gnome Armor", icon: "", imbuingSlots: 2, elements: ["energy"] },
  { name: "Gnomish Cuirass", icon: "", imbuingSlots: 1 },
  { name: "Golden Armor", icon: "", imbuingSlots: 2 },
  { name: "Green Demon Armor", icon: "", imbuingSlots: 2 },
  { name: "Heat Core", icon: "", imbuingSlots: 2 },
  { name: "Heavy Metal T-Shirt", icon: "", imbuingSlots: 2 },
  { name: "Knight Armor", icon: "", imbuingSlots: 2 },
  { name: "Leopard Armor", icon: "", imbuingSlots: 2 },
  { name: "Lion Plate", icon: "", imbuingSlots: 2 },
  { name: "Living Armor", icon: "", imbuingSlots: 1, elements: ["earth"] },
  { name: "Magic Plate Armor", icon: "", imbuingSlots: 2 },
  { name: "Mammoth Fur Cape", icon: "", imbuingSlots: 2 },
  {
    name: "Master Archer's Armor",
    icon: "",
    imbuingSlots: 1,
  },
  { name: "Merudri Battle Mail", icon: "", imbuingSlots: 2, elements: ["earth"] },
  { name: "Merudri Nanbando", icon: "", imbuingSlots: 1 },
  { name: "Midnight Tunic", icon: "", imbuingSlots: 1 },
  { name: "Mooh'tah Plate", icon: "", imbuingSlots: 2 },
  { name: "Mutated Skin Armor", icon: "", imbuingSlots: 2 },
  {
    name: "Mystical Dragon Robe",
    icon: "",
    imbuingSlots: 1,
    elements: ["fire"],
  },
  { name: "Naga Tanko", icon: "", imbuingSlots: 2, elements: ["fire"] },
  { name: "Noble Armor", icon: "", imbuingSlots: 2 },
  { name: "Ornate Chestplate", icon: "", imbuingSlots: 2 },
  { name: "Paladin Armor", icon: "", imbuingSlots: 1 },
  { name: "Prismatic Armor", icon: "", imbuingSlots: 1 },
  {
    name: "Robe of Enlightenment",
    icon: "",
    imbuingSlots: 1,
  },
  { name: "Soulgarb", icon: "", imbuingSlots: 2, elements: ["ice"] },
  { name: "Soulmantle", icon: "", imbuingSlots: 2 },
  { name: "Soulshell", icon: "", imbuingSlots: 2, elements: ["fire"] },
  { name: "Soulshroud", icon: "", imbuingSlots: 2, elements: ["death"] },
  { name: "Spiritthorn Armor", icon: "", imbuingSlots: 2 },
  {
    name: "Stoic Iks Chestplate",
    icon: "",
    imbuingSlots: 2,
  },
  { name: "Stoic Iks Cuirass", icon: "", imbuingSlots: 1, elements: ["death"] },
  { name: "Stoic Iks Robe", icon: "", imbuingSlots: 2, elements: ["energy"] },
  { name: "Toga Mortis", icon: "", imbuingSlots: 1, elements: ["death"] },
  {
    name: "Unerring Dragon Scale Armor",
    icon: "",
    imbuingSlots: 2,
  },
];
