import { ImbuableItem } from "./imbuableItems";

export const axes: ImbuableItem[] = [
  { name: "Amber Axe", icon: "", imbuingSlots: 2 },
  { name: "Amber Greataxe", icon: "", imbuingSlots: 2 },
  { name: "Axe of Carving", icon: "", imbuingSlots: 3 },
  { name: "Axe of Destruction", icon: "", imbuingSlots: 2 },
  { name: "Axe of Mayhem", icon: "", imbuingSlots: 3 },
  { name: "Axe of Remedy", icon: "", imbuingSlots: 3 },
  { name: "Barbarian Axe", icon: "", imbuingSlots: 2 },
  { name: "Beastslayer Axe", icon: "", imbuingSlots: 2 },
  { name: "Butcher's Axe", icon: "", imbuingSlots: 2 },
  { name: "Chopper of Carving", icon: "", imbuingSlots: 3 },
  {
    name: "Chopper of Destruction",
    icon: "",
    imbuingSlots: 3,
  },
  { name: "Chopper of Mayhem", icon: "", imbuingSlots: 3 },
  { name: "Chopper of Remedy", icon: "", imbuingSlots: 3 },
  { name: "Cobra Axe", icon: "", imbuingSlots: 2 },
  { name: "Crystalline Axe", icon: "", imbuingSlots: 1 },
  { name: "Demonwing Axe", icon: "", imbuingSlots: 2 },
  { name: "Dragon Lance", icon: "", imbuingSlots: 3 },
  {
    name: "Draining Inferniarch Battleaxe",
    icon: "",
    imbuingSlots: 1,
  },
  {
    name: "Draining Inferniarch Greataxe",
    icon: "",
    imbuingSlots: 1,
  },
  { name: "Drakinata", icon: "", imbuingSlots: 3 },
  { name: "Dreaded Cleaver", icon: "", imbuingSlots: 2 },
  { name: "Dwarven Axe", icon: "", imbuingSlots: 2 },
  { name: "Eldritch Greataxe", icon: "", imbuingSlots: 2 },
  { name: "Executioner", icon: "", imbuingSlots: 2 },
  { name: "Falcon Battleaxe", icon: "", imbuingSlots: 2 },
  {
    name: "Gilded Eldritch Greataxe",
    icon: "",
    imbuingSlots: 2,
  },
  {
    name: "Grand Sanguine Battleaxe",
    icon: "",
    imbuingSlots: 3,
  },
  {
    name: "Grand Sanguine Hatchet",
    icon: "",
    imbuingSlots: 2,
  },
  { name: "Great Axe", icon: "", imbuingSlots: 2 },
  { name: "Guardian Halberd", icon: "", imbuingSlots: 3 },
  { name: "Headchopper", icon: "", imbuingSlots: 3 },
  { name: "Hellforged Axe", icon: "", imbuingSlots: 1 },
  { name: "Heroic Axe", icon: "", imbuingSlots: 2 },
  { name: "Hive Scythe", icon: "", imbuingSlots: 2 },
  { name: "Impaler", icon: "", imbuingSlots: 2 },
  {
    name: "Inferniarch Battleaxe",
    icon: "",
    imbuingSlots: 2,
  },
  {
    name: "Inferniarch Greataxe",
    icon: "",
    imbuingSlots: 2,
  },
  { name: "Knight Axe", icon: "", imbuingSlots: 2 },
  { name: "Lion Axe", icon: "", imbuingSlots: 2 },
  { name: "Mythril Axe", icon: "", imbuingSlots: 2 },
  { name: "Naga Axe", icon: "", imbuingSlots: 2 },
  { name: "Noble Axe", icon: "", imbuingSlots: 2 },
  { name: "Phantasmal Axe", icon: "", imbuingSlots: 2 },
  { name: "Ravager's Axe", icon: "", imbuingSlots: 3 },
  {
    name: "Rending Inferniarch Battleaxe",
    icon: "",
    imbuingSlots: 1,
  },
  {
    name: "Rending Inferniarch Greataxe",
    icon: "",
    imbuingSlots: 1,
  },
  { name: "Rift Lance", icon: "", imbuingSlots: 3 },
  { name: "Royal Axe", icon: "", imbuingSlots: 2 },
  { name: "Ruthless Axe", icon: "", imbuingSlots: 2 },
  { name: "Sanguine Battleaxe", icon: "", imbuingSlots: 3 },
  { name: "Sanguine Hatchet", icon: "", imbuingSlots: 2 },
  {
    name: "Siphoning Inferniarch Battleaxe",
    icon: "",
    imbuingSlots: 1,
  },
  {
    name: "Siphoning Inferniarch Greataxe",
    icon: "",
    imbuingSlots: 1,
  },
  { name: "Solar Axe", icon: "", imbuingSlots: 1 },
  { name: "Soulbiter", icon: "", imbuingSlots: 2 },
  { name: "Souleater (Axe)", icon: "", imbuingSlots: 3 },
  { name: "Stonecutter Axe", icon: "", imbuingSlots: 1 },
  { name: "Throwing Axe", icon: "", imbuingSlots: 1 },
  { name: "Twin Axe", icon: "", imbuingSlots: 3 },
  { name: "Umbral Axe", icon: "", imbuingSlots: 1 },
  { name: "Umbral Chopper", icon: "", imbuingSlots: 1 },
  { name: "Umbral Master Axe", icon: "", imbuingSlots: 1 },
  {
    name: "Umbral Master Chopper",
    icon: "",
    imbuingSlots: 2,
  },
  { name: "War Axe", icon: "", imbuingSlots: 3 },
  { name: "Warrior's Axe", icon: "", imbuingSlots: 2 },
  { name: "Zaoan Halberd", icon: "", imbuingSlots: 3 },
];
