import { ImbuableItem } from "./imbuableItems";

export const backpacks: ImbuableItem[] = [
  { name: "25 Years Backpack", icon: "", imbuingSlots: 1 },
  {
    name: "Anniversary Backpack",
    icon: "",
    imbuingSlots: 1,
  },
  { name: "Backpack of Holding", icon: "", imbuingSlots: 1 },
  { name: "Backpack", icon: "", imbuingSlots: 1 },
  { name: "Beach Backpack", icon: "", imbuingSlots: 1 },
  { name: "Birthday Backpack", icon: "", imbuingSlots: 1 },
  { name: "Blue Backpack", icon: "", imbuingSlots: 1 },
  { name: "Book Backpack", icon: "", imbuingSlots: 1 },
  { name: "Brocade Backpack", icon: "", imbuingSlots: 1 },
  { name: "Buggy Backpack", icon: "", imbuingSlots: 1 },
  { name: "Bursa Obscura", icon: "", imbuingSlots: 1 },
  { name: "Cake Backpack", icon: "", imbuingSlots: 1 },
  { name: "Camouflage Backpack", icon: "", imbuingSlots: 1 },
  { name: "Changing Backpack", icon: "", imbuingSlots: 1 },
  { name: "Crown Backpack", icon: "", imbuingSlots: 1 },
  { name: "Crystal Backpack", icon: "", imbuingSlots: 1 },
  { name: "Deepling Backpack", icon: "", imbuingSlots: 1 },
  { name: "Demon Backpack", icon: "", imbuingSlots: 1 },
  { name: "Dragon Backpack", icon: "", imbuingSlots: 1 },
  { name: "Energetic Backpack", icon: "", imbuingSlots: 1 },
  { name: "Expedition Backpack", icon: "", imbuingSlots: 1 },
  { name: "Feedbag", icon: "", imbuingSlots: 1 },
  { name: "Festive Backpack", icon: "", imbuingSlots: 1 },
  { name: "Fur Backpack", icon: "", imbuingSlots: 1 },
  { name: "Ghost Backpack", icon: "", imbuingSlots: 1 },
  { name: "Glooth Backpack", icon: "", imbuingSlots: 1 },
  { name: "Golden Backpack", icon: "", imbuingSlots: 1 },
  { name: "Green Backpack", icon: "", imbuingSlots: 1 },
  { name: "Grey Backpack", icon: "", imbuingSlots: 1 },
  { name: "Heart Backpack", icon: "", imbuingSlots: 1 },
  { name: "Jewelled Backpack", icon: "", imbuingSlots: 1 },
  { name: "Lilypad Backpack", icon: "", imbuingSlots: 1 },
  { name: "Minotaur Backpack", icon: "", imbuingSlots: 1 },
  { name: "Moon Backpack", icon: "", imbuingSlots: 1 },
  { name: "Mushroom Backpack", icon: "", imbuingSlots: 1 },
  {
    name: "Old and Used Backpack",
    icon: "",
    imbuingSlots: 1,
  },
  { name: "Orange Backpack", icon: "", imbuingSlots: 1 },
  { name: "Pannier Backpack", icon: "", imbuingSlots: 1 },
  { name: "Peppermint Backpack", icon: "", imbuingSlots: 1 },
  { name: "Pillow Backpack", icon: "", imbuingSlots: 1 },
  { name: "Pirate Backpack", icon: "", imbuingSlots: 1 },
  { name: "Purple Backpack", icon: "", imbuingSlots: 1 },
  { name: "Raccoon Backpack", icon: "", imbuingSlots: 1 },
  { name: "Red Backpack", icon: "", imbuingSlots: 1 },
  { name: "Santa Backpack", icon: "", imbuingSlots: 1 },
  { name: "Winged Backpack", icon: "", imbuingSlots: 1 },
  { name: "Wolf Backpack", icon: "", imbuingSlots: 1 },
  { name: "Yellow Backpack", icon: "", imbuingSlots: 1 },
];
