import { ImbuableItem } from "./imbuableItems";

export const boots: ImbuableItem[] = [
  { name: "Alchemist's Boots", icon: "", imbuingSlots: 1 },
  { name: "Badger Boots", icon: "", imbuingSlots: 1 },
  { name: "Boots of Haste", icon: "", imbuingSlots: 1 },
  { name: "Bunnyslippers", icon: "", imbuingSlots: 1 },
  { name: "Cobra Boots", icon: "", imbuingSlots: 1 },
  { name: "Coconut Shoes", icon: "", imbuingSlots: 1 },
  { name: "Crocodile Boots", icon: "", imbuingSlots: 1 },
  { name: "Crystal Boots", icon: "", imbuingSlots: 1, elements: ["ice"] },
  { name: "Depth Calcei", icon: "", imbuingSlots: 1 },
  { name: "Dragon Scale Boots", icon: "", imbuingSlots: 1, elements: ["fire"] },
  { name: "Draken Boots", icon: "", imbuingSlots: 1 },
  { name: "Eldritch Monk Boots", icon: "", imbuingSlots: 1, elements: ["energy"] },
  { name: "Feverbloom Boots", icon: "", imbuingSlots: 1, elements: ["ice"] },
  { name: "Frostflower Boots", icon: "", imbuingSlots: 1, elements: ["ice"] },
  { name: "Fur Boots", icon: "", imbuingSlots: 1 },
  { name: "Glacier Shoes", icon: "", imbuingSlots: 1, elements: ["ice"] },
  { name: "Gnomish Footwraps", icon: "", imbuingSlots: 1, elements: ["earth"] },
  { name: "Golden Boots", icon: "", imbuingSlots: 1 },
  { name: "Green Demon Slippers", icon: "", imbuingSlots: 1 },
  { name: "Guardian Boots", icon: "", imbuingSlots: 1 },
  { name: "Iks Footwraps", icon: "", imbuingSlots: 1, elements: ["fire"] },
  { name: "Leather Boots", icon: "", imbuingSlots: 1 },
  { name: "Lightning Boots", icon: "", imbuingSlots: 1, elements: ["energy"] },
  { name: "Magma Boots", icon: "", imbuingSlots: 1, elements: ["fire"] },
  { name: "Make-do Boots", icon: "", imbuingSlots: 1, elements: ["ice"] },
  { name: "Makeshift Boots", icon: "", imbuingSlots: 1, elements: ["fire"] },
  { name: "Metal Spats", icon: "", imbuingSlots: 1 },
  { name: "Mutant Bone Boots", icon: "", imbuingSlots: 1, elements: ["death"] },
  { name: "Oriental Shoes", icon: "", imbuingSlots: 1 },
  { name: "Pair of Dreamwalkers", icon: "", imbuingSlots: 1, elements: ["earth"] },
  { name: "Pair of Nightmare Boots", icon: "", imbuingSlots: 1, elements: ["energy"] },
  { name: "Pair of Soulstalkers", icon: "", imbuingSlots: 1 },
  { name: "Pair of Soulwalkers", icon: "", imbuingSlots: 1, elements: ["fire"] },
  { name: "Patched Boots", icon: "", imbuingSlots: 1 },
  { name: "Pirate Boots", icon: "", imbuingSlots: 1 },
  { name: "Prismatic Boots", icon: "", imbuingSlots: 1, elements: ["death"] },
  { name: "Sandals", icon: "", imbuingSlots: 1 },
  { name: "Sanguine Boots", icon: "", imbuingSlots: 1, elements: ["ice"] },
  { name: "Sanguine Galoshes", icon: "", imbuingSlots: 1, elements: ["fire"] },
  { name: "Soulsoles", icon: "", imbuingSlots: 1, elements: ["ice"] },
  { name: "Steel Boots", icon: "", imbuingSlots: 1 },
  { name: "Stoic Iks Boots", icon: "", imbuingSlots: 1, elements: ["fire"] },
  { name: "Stoic Iks Sandals", icon: "", imbuingSlots: 1, elements: ["ice"] },
  { name: "Terra Boots", icon: "", imbuingSlots: 1, elements: ["earth"] },
  { name: "Treader of Torment", icon: "", imbuingSlots: 1 },
  { name: "Vampire Silk Slippers", icon: "", imbuingSlots: 1 },
  { name: "Winged Boots", icon: "", imbuingSlots: 1, elements: ["earth"] },
  { name: "Yalahari Footwraps", icon: "", imbuingSlots: 1, elements: ["death"] },
  { name: "Zaoan Shoes", icon: "", imbuingSlots: 1 },
];
