import { ImbuableItem } from "./imbuableItems";

export const bows: ImbuableItem[] = [
  { name: "Amber Bow", icon: "", imbuingSlots: 3 },
  { name: "Bow of Carving", icon: "", imbuingSlots: 3 },
  { name: "Bow of Cataclysm", icon: "", imbuingSlots: 3 },
  { name: "Bow of Destruction", icon: "", imbuingSlots: 3 },
  { name: "Bow of Mayhem", icon: "", imbuingSlots: 3 },
  { name: "Bow of Remedy", icon: "", imbuingSlots: 3 },
  { name: "Composite Hornbow", icon: "", imbuingSlots: 3 },
  {
    name: "Draining Inferniarch Bow",
    icon: "",
    imbuingSlots: 2,
  },
  { name: "Eldritch Bow", icon: "", imbuingSlots: 3 },
  { name: "Elvish Bow", icon: "", imbuingSlots: 3 },
  { name: "Falcon Bow", icon: "", imbuingSlots: 3 },
  { name: "Gilded Eldritch Bow", icon: "", imbuingSlots: 3 },
  { name: "Grand Sanguine Bow", icon: "", imbuingSlots: 3 },
  { name: "Hive Bow", icon: "", imbuingSlots: 3 },
  { name: "Icicle Bow", icon: "", imbuingSlots: 3 },
  { name: "Inferniarch Bow", icon: "", imbuingSlots: 3 },
  { name: "Jungle Bow", icon: "", imbuingSlots: 2 },
  { name: "Lion Longbow", icon: "", imbuingSlots: 3 },
  { name: "Living Vine Bow", icon: "", imbuingSlots: 3 },
  { name: "Musician's Bow", icon: "", imbuingSlots: 3 },
  { name: "Mycological Bow", icon: "", imbuingSlots: 3 },
  {
    name: "Rending Inferniarch Bow",
    icon: "",
    imbuingSlots: 2,
  },
  { name: "Rift Bow", icon: "", imbuingSlots: 3 },
  { name: "Sanguine Bow", icon: "", imbuingSlots: 3 },
  { name: "Silkweaver Bow", icon: "", imbuingSlots: 3 },
  {
    name: "Siphoning Inferniarch Bow",
    icon: "",
    imbuingSlots: 2,
  },
  { name: "Soulbleeder", icon: "", imbuingSlots: 3 },
  { name: "Umbral Bow", icon: "", imbuingSlots: 1 },
  { name: "Umbral Master Bow", icon: "", imbuingSlots: 2 },
  { name: "Warsinger Bow", icon: "", imbuingSlots: 3 },
];
