import { ImbuableItem } from "./imbuableItems";

export const clubs: ImbuableItem[] = [
  { name: "Abyss Hammer", icon: "", imbuingSlots: 3 },
  { name: "Amber Bludgeon", icon: "", imbuingSlots: 2 },
  { name: "Amber Cudgel", icon: "", imbuingSlots: 2 },
  { name: "Amber Staff", icon: "", imbuingSlots: 3 },
  { name: "Arcane Staff", icon: "", imbuingSlots: 2 },
  { name: "Blessed Sceptre", icon: "", imbuingSlots: 2 },
  { name: "Clerical Mace", icon: "", imbuingSlots: 2 },
  { name: "Cobra Club", icon: "", imbuingSlots: 2 },
  { name: "Cranial Basher", icon: "", imbuingSlots: 2 },
  { name: "Crystal Mace", icon: "", imbuingSlots: 2 },
  { name: "Deepling Squelcher", icon: "", imbuingSlots: 2 },
  { name: "Demonbone", icon: "", imbuingSlots: 2 },
  { name: "Dragonbone Staff", icon: "", imbuingSlots: 2 },
  {
    name: "Draining Inferniarch Flail",
    icon: "",
    imbuingSlots: 1,
  },
  {
    name: "Draining Inferniarch Warhammer",
    icon: "",
    imbuingSlots: 1,
  },
  { name: "Eldritch Warmace", icon: "", imbuingSlots: 2 },
  { name: "Energized Demonbone", icon: "", imbuingSlots: 2 },
  { name: "Falcon Mace", icon: "", imbuingSlots: 2 },
  {
    name: "Gilded Eldritch Warmace",
    icon: "",
    imbuingSlots: 2,
  },
  { name: "Glooth Whip", icon: "", imbuingSlots: 2 },
  {
    name: "Grand Sanguine Bludgeon",
    icon: "",
    imbuingSlots: 3,
  },
  {
    name: "Grand Sanguine Cudgel",
    icon: "",
    imbuingSlots: 2,
  },
  { name: "Hammer of Carving", icon: "", imbuingSlots: 3 },
  {
    name: "Hammer of Destruction",
    icon: "",
    imbuingSlots: 3,
  },
  { name: "Hammer of Mayhem", icon: "", imbuingSlots: 3 },
  { name: "Hammer of Remedy", icon: "", imbuingSlots: 3 },
  { name: "Hammer of Wrath", icon: "", imbuingSlots: 3 },
  { name: "Heavy Mace", icon: "", imbuingSlots: 3 },
  { name: "Inferniarch Flail", icon: "", imbuingSlots: 2 },
  {
    name: "Inferniarch Warhammer",
    icon: "",
    imbuingSlots: 2,
  },
  { name: "Jungle Flail", icon: "", imbuingSlots: 2 },
  { name: "Life Preserver", icon: "", imbuingSlots: 2 },
  { name: "Lion Hammer", icon: "", imbuingSlots: 2 },
  { name: "Lunar Staff", icon: "", imbuingSlots: 3 },
  { name: "Mace of Carving", icon: "", imbuingSlots: 3 },
  { name: "Mace of Destruction", icon: "", imbuingSlots: 2 },
  { name: "Mace of Mayhem", icon: "", imbuingSlots: 3 },
  { name: "Mace of Remedy", icon: "", imbuingSlots: 3 },
  { name: "Maimer", icon: "", imbuingSlots: 1 },
  { name: "Mortal Mace", icon: "", imbuingSlots: 2 },
  { name: "Mycological Mace", icon: "", imbuingSlots: 1 },
  { name: "Naga Club", icon: "", imbuingSlots: 2 },
  { name: "Obsidian Truncheon", icon: "", imbuingSlots: 1 },
  { name: "Onyx Flail", icon: "", imbuingSlots: 2 },
  { name: "Orcish Maul", icon: "", imbuingSlots: 3 },
  { name: "Ornate Mace", icon: "", imbuingSlots: 2 },
  { name: "Queen's Sceptre", icon: "", imbuingSlots: 2 },
  {
    name: "Rending Inferniarch Flail",
    icon: "",
    imbuingSlots: 1,
  },
  {
    name: "Rending Inferniarch Warhammer",
    icon: "",
    imbuingSlots: 1,
  },
  { name: "Resizer", icon: "", imbuingSlots: 2 },
  { name: "Rotten Demonbone", icon: "", imbuingSlots: 2 },
  { name: "Sanguine Bludgeon", icon: "", imbuingSlots: 3 },
  { name: "Sanguine Cudgel", icon: "", imbuingSlots: 2 },
  { name: "Sapphire Hammer", icon: "", imbuingSlots: 2 },
  { name: "Shadow Sceptre", icon: "", imbuingSlots: 2 },
  { name: "Silver Mace", icon: "", imbuingSlots: 2 },
  {
    name: "Siphoning Inferniarch Flail",
    icon: "",
    imbuingSlots: 1,
  },
  {
    name: "Siphoning Inferniarch Warhammer",
    icon: "",
    imbuingSlots: 1,
  },
  { name: "Skull Staff", icon: "", imbuingSlots: 2 },
  { name: "Skullcrusher", icon: "", imbuingSlots: 2 },
  { name: "Snake God's Sceptre", icon: "", imbuingSlots: 2 },
  { name: "Soulcrusher", icon: "", imbuingSlots: 2 },
  { name: "Soulmaimer", icon: "", imbuingSlots: 3 },
  { name: "Spiked Squelcher", icon: "", imbuingSlots: 3 },
  {
    name: "Sulphurous Demonbone",
    icon: "",
    imbuingSlots: 2,
  },
  { name: "The Stomper", icon: "", imbuingSlots: 2 },
  { name: "Thunder Hammer", icon: "", imbuingSlots: 2 },
  { name: "Umbral Hammer", icon: "", imbuingSlots: 1 },
  { name: "Umbral Mace", icon: "", imbuingSlots: 1 },
  {
    name: "Umbral Master Hammer",
    icon: "",
    imbuingSlots: 2,
  },
  { name: "Umbral Master Mace", icon: "", imbuingSlots: 1 },
  { name: "Unliving Demonbone", icon: "", imbuingSlots: 2 },
  { name: "War Hammer", icon: "", imbuingSlots: 3 },
];
