import { ImbuableItem } from "./imbuableItems";

export const helmets: ImbuableItem[] = [
  { name: "Alicorn Headguard", icon: "", imbuingSlots: 2, elements: ["fire", "earth", "energy", "ice", "holy", "death"] },
  { name: "Amazon Helmet", icon: "", imbuingSlots: 2 },
  { name: "Ancient Tiara", icon: "", imbuingSlots: 2 },
  { name: "Antler-Horn Helmet", icon: "", imbuingSlots: 2 },
  { name: "Arboreal Crown", icon: "", imbuingSlots: 2, elements: ["ice"] },
  { name: "Arcanomancer Regalia", icon: "", imbuingSlots: 2, elements: ["earth"] },
  { name: "Batwing Hat", icon: "", imbuingSlots: 1 },
  { name: "Bonelord Helmet", icon: "", imbuingSlots: 2 },
  { name: "Cobra Hood", icon: "", imbuingSlots: 2 },
  { name: "Coned Hat of Enlightenment", icon: "", imbuingSlots: 1 },
  { name: "Coned Hat of Spirits", icon: "", imbuingSlots: 2 },
  { name: "Crown Helmet", icon: "", imbuingSlots: 2 },
  { name: "Crusader Helmet", icon: "", imbuingSlots: 2 },
  { name: "Dark Vision Bandana", icon: "", imbuingSlots: 2, elements: ["energy"] },
  { name: "Dark Whispers", icon: "", imbuingSlots: 2, elements: ["ice"] },
  { name: "Demon Helmet", icon: "", imbuingSlots: 2 },
  { name: "Demon Mengu", icon: "", imbuingSlots: 2, elements: ["death"] },
  { name: "Demonfang Mask", icon: "", imbuingSlots: 2, elements: ["death"] },
  { name: "Dreadfire Headpiece", icon: "", imbuingSlots: 2, elements: ["death"] },
  { name: "Dwarven Helmet", icon: "", imbuingSlots: 2 },
  { name: "Eldritch Cowl", icon: "", imbuingSlots: 2, elements: ["ice"] },
  { name: "Eldritch Hood", icon: "", imbuingSlots: 2, elements: ["earth"] },
  { name: "Elite Draken Helmet", icon: "", imbuingSlots: 1, elements: ["death"] },
  { name: "Falcon Circlet", icon: "", imbuingSlots: 2, elements: ["fire"] },
  { name: "Falcon Coif", icon: "", imbuingSlots: 2, elements: ["fire"] },
  { name: "Fur Cap", icon: "", imbuingSlots: 2 },
  { name: "Galea Mortis", icon: "", imbuingSlots: 2, elements: ["death"] },
  { name: "Gnome Helmet", icon: "", imbuingSlots: 2, elements: ["energy"] },
  { name: "Golden Helmet", icon: "", imbuingSlots: 2 },
  { name: "Green Demon Helmet", icon: "", imbuingSlots: 2 },
  { name: "Hat of the Mad", icon: "", imbuingSlots: 1 },
  { name: "Hellstalker Visor", icon: "", imbuingSlots: 2, elements: ["death"] },
  { name: "Helmet of Nature", icon: "", imbuingSlots: 2 },
  { name: "Helmet of Ultimate Terror", icon: "", imbuingSlots: 2 },
  { name: "Helmet of the Lost", icon: "", imbuingSlots: 2 },
  { name: "Jade Conical Hat", icon: "", imbuingSlots: 1, elements: ["ice"] },
  { name: "Jade Hat", icon: "", imbuingSlots: 1 },
  { name: "Lion Spangenhelm", icon: "", imbuingSlots: 2, elements: ["earth"] },
  { name: "Mage Hat", icon: "", imbuingSlots: 2 },
  { name: "Magician Hat", icon: "", imbuingSlots: 2 },
  { name: "Maliceforged Helmet", icon: "", imbuingSlots: 2, elements: ["death"] },
  { name: "Odd Hat", icon: "", imbuingSlots: 2 },
  { name: "Royal Helmet", icon: "", imbuingSlots: 2 },
  { name: "Shamanic Mask", icon: "", imbuingSlots: 2 },
  { name: "Skull Helmet", icon: "", imbuingSlots: 2 },
  { name: "Spiritthorn Helmet", icon: "", imbuingSlots: 2, elements: ["energy"] },
  { name: "Stoic Iks Casque", icon: "", imbuingSlots: 2, elements: ["energy"] },
  { name: "Stoic Iks Headpiece", icon: "", imbuingSlots: 2, elements: ["death"] },
  { name: "Terra Helmet", icon: "", imbuingSlots: 1, elements: ["earth"] },
  { name: "Visage of the End Days", icon: "", imbuingSlots: 2 },
  { name: "Warrior Helmet", icon: "", imbuingSlots: 2 },
  { name: "Witch Hat", icon: "", imbuingSlots: 1 },
  { name: "Yalahari Mask", icon: "", imbuingSlots: 1 },
  { name: "Zaoan Helmet", icon: "", imbuingSlots: 1 },
];
