import { ImbuableItem } from "./imbuableItems";

export const shields: ImbuableItem[] = [
  { name: "Amazon Shield", icon: "", imbuingSlots: 1 },
  { name: "Biscuit Barrier", icon: "", imbuingSlots: 1 },
  { name: "Bonelord Shield", icon: "", imbuingSlots: 1 },
  { name: "Carapace Shield", icon: "", imbuingSlots: 1 },
  { name: "Castle Shield", icon: "", imbuingSlots: 1 },
  { name: "Crown Shield", icon: "", imbuingSlots: 1 },
  { name: "Death Gaze", icon: "", imbuingSlots: 1 },
  { name: "Demon Shield", icon: "", imbuingSlots: 1 },
  { name: "Depth Scutum", icon: "", imbuingSlots: 1 },
  { name: "Dragon Shield", icon: "", imbuingSlots: 1 },
  { name: "Ectoplasmic Shield", icon: "", imbuingSlots: 1 },
  { name: "Eldritch Shield", icon: "", imbuingSlots: 1 },
  { name: "Falcon Escutcheon", icon: "", imbuingSlots: 1 },
  { name: "Falcon Shield", icon: "", imbuingSlots: 1 },
  { name: "Gnome Shield", icon: "", imbuingSlots: 1 },
  { name: "Great Shield", icon: "", imbuingSlots: 1 },
  { name: "Griffin Shield", icon: "", imbuingSlots: 1 },
  {
    name: "Haunted Mirror Piece",
    icon: "",
    imbuingSlots: 1,
  },
  { name: "Lion Shield", icon: "", imbuingSlots: 1 },
  { name: "Mastermind Shield", icon: "", imbuingSlots: 1 },
  { name: "Meat Shield", icon: "", imbuingSlots: 1 },
  { name: "Medusa Shield", icon: "", imbuingSlots: 1 },
  { name: "Necromancer Shield", icon: "", imbuingSlots: 1 },
  { name: "Nightmare Shield", icon: "", imbuingSlots: 1 },
  { name: "Norse Shield", icon: "", imbuingSlots: 1 },
  { name: "Ornamented Shield", icon: "", imbuingSlots: 1 },
  { name: "Ornate Shield", icon: "", imbuingSlots: 1 },
  { name: "Phoenix Shield", icon: "", imbuingSlots: 1 },
  { name: "Rift Shield", icon: "", imbuingSlots: 1 },
  { name: "Runic Ice Shield", icon: "", imbuingSlots: 1 },
  { name: "Sentinel Shield", icon: "", imbuingSlots: 1 },
  { name: "Shield of Care", icon: "", imbuingSlots: 1 },
  {
    name: "Shield of Corruption",
    icon: "",
    imbuingSlots: 1,
  },
  {
    name: "Shield of the White Knight",
    icon: "",
    imbuingSlots: 1,
  },
  { name: "Soulbastion", icon: "", imbuingSlots: 1 },
  { name: "Steel Shield", icon: "", imbuingSlots: 1 },
  { name: "Tempest Shield", icon: "", imbuingSlots: 1 },
  { name: "Tower Shield", icon: "", imbuingSlots: 1 },
  { name: "Vampire Shield", icon: "", imbuingSlots: 1 },
  { name: "Viking Shield", icon: "", imbuingSlots: 1 },
  { name: "Warrior's Shield", icon: "", imbuingSlots: 1 },
];
