import { ImbuableItem } from "./imbuableItems";

export const swords: ImbuableItem[] = [
  { name: "Amber Sabre", icon: "", imbuingSlots: 2 },
  { name: "Amber Slayer", icon: "", imbuingSlots: 2 },
  { name: "Assassin Dagger", icon: "", imbuingSlots: 2 },
  { name: "Berserker", icon: "", imbuingSlots: 3 },
  { name: "Blacksteel Sword", icon: "", imbuingSlots: 3 },
  { name: "Blade of Carving", icon: "", imbuingSlots: 3 },
  { name: "Blade of Corruption", icon: "", imbuingSlots: 2 },
  {
    name: "Blade of Destruction",
    icon: "",
    imbuingSlots: 2,
  },
  { name: "Blade of Mayhem", icon: "", imbuingSlots: 3 },
  { name: "Blade of Remedy", icon: "", imbuingSlots: 3 },
  { name: "Bloody Edge", icon: "", imbuingSlots: 2 },
  { name: "Bright Sword", icon: "", imbuingSlots: 2 },
  { name: "Broadsword", icon: "", imbuingSlots: 3 },
  { name: "Cobra Sword", icon: "", imbuingSlots: 2 },
  { name: "Crimson Sword", icon: "", imbuingSlots: 2 },
  { name: "Demonrage Sword", icon: "", imbuingSlots: 3 },
  { name: "Djinn Blade", icon: "", imbuingSlots: 2 },
  { name: "Dragon Slayer", icon: "", imbuingSlots: 3 },
  {
    name: "Draining Inferniarch Blade",
    icon: "",
    imbuingSlots: 1,
  },
  {
    name: "Draining Inferniarch Slayer",
    icon: "",
    imbuingSlots: 1,
  },
  { name: "Eldritch Claymore", icon: "", imbuingSlots: 2 },
  { name: "Emerald Sword", icon: "", imbuingSlots: 2 },
  { name: "Epee", icon: "", imbuingSlots: 2 },
  { name: "Falcon Longsword", icon: "", imbuingSlots: 2 },
  { name: "Giant Sword", icon: "", imbuingSlots: 3 },
  {
    name: "Gilded Eldritch Claymore",
    icon: "",
    imbuingSlots: 2,
  },
  { name: "Gnome Sword", icon: "", imbuingSlots: 2 },
  {
    name: "Grand Sanguine Blade",
    icon: "",
    imbuingSlots: 2,
  },
  {
    name: "Grand Sanguine Razor",
    icon: "",
    imbuingSlots: 3,
  },
  { name: "Haunted Blade", icon: "", imbuingSlots: 3 },
  { name: "Havoc Blade", icon: "", imbuingSlots: 3 },
  { name: "Inferniarch Blade", icon: "", imbuingSlots: 2 },
  { name: "Inferniarch Slayer", icon: "", imbuingSlots: 2 },
  { name: "Lion Longsword", icon: "", imbuingSlots: 2 },
  { name: "Magic Sword", icon: "", imbuingSlots: 2 },
  { name: "Mystic Blade", icon: "", imbuingSlots: 2 },
  { name: "Naga Sword", icon: "", imbuingSlots: 2 },
  { name: "Nightmare Blade", icon: "", imbuingSlots: 2 },
  { name: "Relic Sword", icon: "", imbuingSlots: 2 },
  {
    name: "Rending Inferniarch Blade",
    icon: "",
    imbuingSlots: 1,
  },
  {
    name: "Rending Inferniarch Slayer",
    icon: "",
    imbuingSlots: 1,
  },
  { name: "Runed Sword", icon: "", imbuingSlots: 2 },
  { name: "Sanguine Blade", icon: "", imbuingSlots: 2 },
  { name: "Sanguine Razor", icon: "", imbuingSlots: 3 },
  { name: "Shiny Blade", icon: "", imbuingSlots: 1 },
  {
    name: "Siphoning Inferniarch Blade",
    icon: "",
    imbuingSlots: 1,
  },
  {
    name: "Siphoning Inferniarch Slayer",
    icon: "",
    imbuingSlots: 1,
  },
  { name: "Slayer of Carving", icon: "", imbuingSlots: 3 },
  {
    name: "Slayer of Destruction",
    icon: "",
    imbuingSlots: 3,
  },
  { name: "Slayer of Mayhem", icon: "", imbuingSlots: 3 },
  { name: "Slayer of Remedy", icon: "", imbuingSlots: 3 },
  { name: "Soulcutter", icon: "", imbuingSlots: 2 },
  { name: "Soulshredder", icon: "", imbuingSlots: 3 },
  { name: "Spike Sword", icon: "", imbuingSlots: 2 },
  { name: "Summerblade", icon: "", imbuingSlots: 2 },
  { name: "Sword", icon: "", imbuingSlots: 2 },
  { name: "Tagralt Blade", icon: "", imbuingSlots: 2 },
  { name: "Thaian Sword", icon: "", imbuingSlots: 3 },
  { name: "The Avenger", icon: "", imbuingSlots: 2 },
  { name: "The Epiphany", icon: "", imbuingSlots: 1 },
  { name: "Twiceslicer", icon: "", imbuingSlots: 3 },
  { name: "Twin Hooks", icon: "", imbuingSlots: 3 },
  { name: "Umbral Blade", icon: "", imbuingSlots: 1 },
  {
    name: "Umbral Master Slayer",
    icon: "",
    imbuingSlots: 2,
  },
  { name: "Umbral Masterblade", icon: "", imbuingSlots: 1 },
  { name: "Umbral Slayer", icon: "", imbuingSlots: 1 },
  { name: "Winterblade", icon: "", imbuingSlots: 2 },
  { name: "Wyvern Fang", icon: "", imbuingSlots: 2 },
  { name: "Zaoan Sword", icon: "", imbuingSlots: 2 },
];
